### ISSUE TITLE
Option to assign bluffs randomly

### ISSUE THREAD

**Issue by ivanhoe1403** [Skateside/pocket-grimoire#108] opened 2024-05-14 13:09 UTC
Would it be possible to assign bluffs randomly? 
It's possible to randomly assign the characters in play, so wondering if the same could be enabled for bluffs...

**Comment by Skateside** [comment] 2024-05-25 08:38
I'm going to close this because it's basically a duplicate of #101

**Closed by Skateside** 2024-05-25 08:38 UTC
